
Attempting with retry: make prepare
Exception calling "DownloadFile" with "2" argument(s): "The remote server 
returned an error: (404) Not Found."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadFile('https://static.rust-l ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
