{"url": "https://api.github.com/repos/rust-lang/rust/issues/103032", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/103032/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/103032/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/103032/events", "html_url": "https://github.com/rust-lang/rust/issues/103032", "id": 1408603796, "node_id": "I_kwDOAAsO6M5T9ZaU", "number": 103032, "title": "Line numbers in error messages?", "user": {"login": "kubycsolutions", "id": 60112771, "node_id": "MDQ6VXNlcjYwMTEyNzcx", "avatar_url": "https://avatars.githubusercontent.com/u/60112771?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kubycsolutions", "html_url": "https://github.com/kubycsolutions", "followers_url": "https://api.github.com/users/kubycsolutions/followers", "following_url": "https://api.github.com/users/kubycsolutions/following{/other_user}", "gists_url": "https://api.github.com/users/kubycsolutions/gists{/gist_id}", "starred_url": "https://api.github.com/users/kubycsolutions/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kubycsolutions/subscriptions", "organizations_url": "https://api.github.com/users/kubycsolutions/orgs", "repos_url": "https://api.github.com/users/kubycsolutions/repos", "events_url": "https://api.github.com/users/kubycsolutions/events{/privacy}", "received_events_url": "https://api.github.com/users/kubycsolutions/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 235791, "node_id": "MDU6TGFiZWwyMzU3OTE=", "url": "https://api.github.com/repos/rust-lang/rust/labels/A-diagnostics", "name": "A-diagnostics", "color": "f7e101", "default": false, "description": "Area: Messages for errors, warnings, and lints"}, {"id": 211668100, "node_id": "MDU6TGFiZWwyMTE2NjgxMDA=", "url": "https://api.github.com/repos/rust-lang/rust/labels/T-compiler", "name": "T-compiler", "color": "bfd4f2", "default": false, "description": "Relevant to the compiler team, which will review and decide on the PR/issue."}, {"id": 650731663, "node_id": "MDU6TGFiZWw2NTA3MzE2NjM=", "url": "https://api.github.com/repos/rust-lang/rust/labels/C-bug", "name": "C-bug", "color": "f5f1fd", "default": false, "description": "Category: This is a bug."}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2022-10-14T01:02:46Z", "updated_at": "2022-10-14T09:01:07Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "(Caveat: Experienced coder, rust novice.)\r\n\r\nI tried running `cargo build` on this `lib.rs` file (very slightly modified from what's in the beta version of the book rewrite):\r\n\r\n```\r\nmod outermost { // private but parent module can see it\r\n    pub fn middle_function() {} // public, accessed through outmost, so visible\r\n\r\n    fn middle_secret_function() {} // private, visible only here or in child mod\r\n\r\n    mod inside {\t\t// private\r\n        pub fn inner_function() {\r\n\t    // Leading :: means start with root module for this library\r\n\t    // msf visible to \"child module of module containing the function\"\r\n\t    ::outermost::middle_secret_function(); // should work\r\n\t} \r\n\r\n\tmod innermost {\r\n\t  pub fn inner_function() {\r\n\t    // The rule really does seem to be child, not descendant...?\r\n\t    ::outermost::middle_secret_function(); // should err if child only\r\n\t  }\r\n\t}\r\n\r\n        fn secret_function() {}\r\n    }\r\n}\r\n\r\nfn try_me() {\t// In root module\r\n    outermost::middle_function(); // should work\r\n    \r\n    // compilation error expected; root is neither current or child of outermost\r\n    outermost::middle_secret_function(); // should err\r\n\r\n    // error expected; non-public module inside.\r\n    outermost::inside::inner_function(); // should err\r\n    // error expected; non-public module AND function.\r\n    outermost::inside::secret_function(); // should err\r\n}\r\n```\r\n\r\nI expected to see errors reported on lines 28, 31, and 33 (the ones marked `// should err`)\r\n\r\nInstead, the errors seem to be being reported on lines 17, 20, and 21, assuming I'm understanding your error syntax correctly:\r\n```\r\nCompiling sample_library v0.1.0 (C:\\Users\\keshlam\\rust\\sample_library)\r\nerror[E0603]: function `middle_secret_function` is private\r\n  --> src\\lib.rs:17:16\r\n   |\r\n17 |     outermost::middle_secret_function();\r\n   |                ^^^^^^^^^^^^^^^^^^^^^^ private function\r\n   |\r\nnote: the function `middle_secret_function` is defined here\r\n  --> src\\lib.rs:4:5\r\n   |\r\n4  |     fn middle_secret_function() {} // private, visible only here or in child mod\r\n   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n\r\nerror[E0603]: module `inside` is private\r\n  --> src\\lib.rs:20:16\r\n   |\r\n20 |     outermost::inside::inner_function();\r\n   |                ^^^^^^ private module\r\n   |\r\nnote: the module `inside` is defined here\r\n  --> src\\lib.rs:6:5\r\n   |\r\n6  |     mod inside {        // private\r\n   |     ^^^^^^^^^^\r\n\r\nerror[E0603]: module `inside` is private\r\n  --> src\\lib.rs:21:16\r\n   |\r\n21 |     outermost::inside::secret_function();\r\n   |                ^^^^^^ private module\r\n   |\r\nnote: the module `inside` is defined here\r\n  --> src\\lib.rs:6:5\r\n   |\r\n6  |     mod inside {        // private\r\n   |     ^^^^^^^^^^\r\n\r\nFor more information about this error, try `rustc --explain E0603`.\r\nerror: could not compile `sample_library` due to 3 previous errors\r\n```\r\n\r\nIs the error report not counting blank lines/comment-only lines?  Or is something else going on here?\r\n\r\nHaven't yet checked the nightly/beta builds.\r\n\r\n### Meta\r\n<!--\r\nIf you're using the stable version of the compiler, you should also check if the\r\nbug also exists in the beta or nightly versions.\r\n-->\r\n\r\n`rustc --version --verbose`:\r\n```\r\nrustc 1.64.0 (a55dd71d5 2022-09-19)\r\nbinary: rustc\r\ncommit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\r\ncommit-date: 2022-09-19\r\nhost: x86_64-pc-windows-msvc\r\nrelease: 1.64.0\r\nLLVM version: 14.0.6\r\n```\r\n\r\nRunning set `RUST_BACKTRACE=1 && cargo build` doesn't yield any additional information.\r\n\r\n", "closed_by": null, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/103032/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/103032/timeline", "performed_via_github_app": null, "state_reason": null}