{"url": "https://api.github.com/repos/rust-lang/rust/issues/36095", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/36095/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/36095/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/36095/events", "html_url": "https://github.com/rust-lang/rust/issues/36095", "id": 173692870, "node_id": "MDU6SXNzdWUxNzM2OTI4NzA=", "number": 36095, "title": "Weird (and possibly wrong) E0308", "user": {"login": "glandium", "id": 1038527, "node_id": "MDQ6VXNlcjEwMzg1Mjc=", "avatar_url": "https://avatars.githubusercontent.com/u/1038527?v=4", "gravatar_id": "", "url": "https://api.github.com/users/glandium", "html_url": "https://github.com/glandium", "followers_url": "https://api.github.com/users/glandium/followers", "following_url": "https://api.github.com/users/glandium/following{/other_user}", "gists_url": "https://api.github.com/users/glandium/gists{/gist_id}", "starred_url": "https://api.github.com/users/glandium/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/glandium/subscriptions", "organizations_url": "https://api.github.com/users/glandium/orgs", "repos_url": "https://api.github.com/users/glandium/repos", "events_url": "https://api.github.com/users/glandium/events{/privacy}", "received_events_url": "https://api.github.com/users/glandium/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 235791, "node_id": "MDU6TGFiZWwyMzU3OTE=", "url": "https://api.github.com/repos/rust-lang/rust/labels/A-diagnostics", "name": "A-diagnostics", "color": "f7e101", "default": false, "description": "Area: Messages for errors, warnings, and lints"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-08-29T04:10:51Z", "updated_at": "2016-08-29T17:03:43Z", "closed_at": "2016-08-29T17:03:43Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Continuing after issue 36092, I ended up with the following code:\n\n``` rust\nuse std::iter::{Iterator,Peekable};\n\ntrait PeekableTrait {\n    type Item;\n    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator;\n}\n\nimpl<I: Iterator> PeekableTrait for Peekable<I> {\n    type Item = I::Item;\n    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator {\n        Peekable::peek(&mut self)\n    }\n}\n```\n\nCompiling it fails with:\n\n```\nerror: main function not found\n\nerror[E0308]: mismatched types\n  --> <anon>:11:9\n   |\n11 |         Peekable::peek(&mut self)\n   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::iter::Peekable`, found type parameter\n   |\n   = note: expected type `std::option::Option<&<std::iter::Peekable<I> as std::iter::Iterator>::Item>`\n   = note:    found type `std::option::Option<&<I as std::iter::Iterator>::Item>`\n\nerror: aborting due to previous error\n```\n\nFWIW, because this was created incrementally, it turns out the type Item is not necessary, and removing it doesn't change anything.\n\nAnyways, talchas on irc figured how to make it compile:\n\n``` rust\nuse std::iter::{Iterator,Peekable};\n\ntrait PeekableTrait: Iterator {\n    fn peek(&mut self) -> Option<&<Self as Iterator>::Item>;\n}\n\nimpl<I: Iterator> PeekableTrait for Peekable<I> {\n    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> {\n        Peekable::peek(&mut self)\n    }\n}\n```\n\nBut simply adding redundant `where Self: ITerator` clauses causes the same E0308 error:\n\n``` rust\nuse std::iter::{Iterator,Peekable};\n\ntrait PeekableTrait: Iterator {\n    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator;\n}\n\nimpl<I: Iterator> PeekableTrait for Peekable<I> {\n    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator {\n        Peekable::peek(&mut self)\n    }\n}\n```\n\nRelatedly, the message `expected struct `std::iter::Peekable`, found type parameter` doesn't make sense to me and I can't reconcile it with the notes that follow it (expected type... found type...)\n", "closed_by": {"login": "arielb1", "id": 1830974, "node_id": "MDQ6VXNlcjE4MzA5NzQ=", "avatar_url": "https://avatars.githubusercontent.com/u/1830974?v=4", "gravatar_id": "", "url": "https://api.github.com/users/arielb1", "html_url": "https://github.com/arielb1", "followers_url": "https://api.github.com/users/arielb1/followers", "following_url": "https://api.github.com/users/arielb1/following{/other_user}", "gists_url": "https://api.github.com/users/arielb1/gists{/gist_id}", "starred_url": "https://api.github.com/users/arielb1/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/arielb1/subscriptions", "organizations_url": "https://api.github.com/users/arielb1/orgs", "repos_url": "https://api.github.com/users/arielb1/repos", "events_url": "https://api.github.com/users/arielb1/events{/privacy}", "received_events_url": "https://api.github.com/users/arielb1/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/36095/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/36095/timeline", "performed_via_github_app": null, "state_reason": "completed"}