{"url": "https://api.github.com/repos/rust-lang/rust/issues/83631", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/83631/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/83631/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/83631/events", "html_url": "https://github.com/rust-lang/rust/issues/83631", "id": 842945673, "node_id": "MDU6SXNzdWU4NDI5NDU2NzM=", "number": 83631, "title": "Future is not Send as this value is used across an await (even though I explicitly drop the value)", "user": {"login": "vedantroy", "id": 8407819, "node_id": "MDQ6VXNlcjg0MDc4MTk=", "avatar_url": "https://avatars.githubusercontent.com/u/8407819?v=4", "gravatar_id": "", "url": "https://api.github.com/users/vedantroy", "html_url": "https://github.com/vedantroy", "followers_url": "https://api.github.com/users/vedantroy/followers", "following_url": "https://api.github.com/users/vedantroy/following{/other_user}", "gists_url": "https://api.github.com/users/vedantroy/gists{/gist_id}", "starred_url": "https://api.github.com/users/vedantroy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/vedantroy/subscriptions", "organizations_url": "https://api.github.com/users/vedantroy/orgs", "repos_url": "https://api.github.com/users/vedantroy/repos", "events_url": "https://api.github.com/users/vedantroy/events{/privacy}", "received_events_url": "https://api.github.com/users/vedantroy/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 650731663, "node_id": "MDU6TGFiZWw2NTA3MzE2NjM=", "url": "https://api.github.com/repos/rust-lang/rust/labels/C-bug", "name": "C-bug", "color": "f5f1fd", "default": false, "description": "Category: This is a bug."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2021-03-29T04:05:01Z", "updated_at": "2021-03-29T10:13:26Z", "closed_at": "2021-03-29T10:13:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "<!--\r\nThank you for filing a bug report! \ud83d\udc1b Please provide a short summary of the bug,\r\nalong with any information you feel relevant to replicating the bug.\r\n-->\r\n\r\nReference rustlang forums question: https://users.rust-lang.org/t/future-is-not-send-as-this-value-is-used-across-an-await-but-i-drop-the-value-before-the-await/57574\r\n\r\nI tried this code:\r\n\r\n```rust\r\nasync fn process(url: Url) -> Result<()> {\r\n    let bytes = fetch(url.clone()).await?;\r\n    let page = String::from_utf8(bytes.clone())?;\r\n    let page = kuchiki::parse_html().one(page);\r\n\r\n    drop(page);\r\n    let links: Vec<Url> = vec![];\r\n    for url in &links {\r\n        add_url(&url).await.unwrap();\r\n    }\r\n    Ok(())\r\n}\r\n```\r\n\r\nI expected to see this happen: *this could should compile (assuming there are no compile errors outside of this function)*<!--\r\nIf you're using the stable version of the compiler, you should also check if the\r\nbug also exists in the beta or nightly versions.\r\n-->\r\n\r\nInstead, this happened:\r\nI get the following error. This error seems confusing because I explicitly `drop` `page` before the `await`.\r\n\r\nFurthermore, in a different code sample (presented below this error message) that does the same thing (I think), this error does not show up.\r\n```\r\nerror: future cannot be sent between threads safely\r\n   --> src/main.rs:310:22\r\n    |\r\n310 |         let handle = tokio::spawn(async move {\r\n    |                      ^^^^^^^^^^^^ future created by async block is not `Send`\r\n    | \r\n   ::: /home/vedantroy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/task/spawn.rs:129:21\r\n    |\r\n129 |         T: Future + Send + 'static,\r\n    |                     ---- required by this bound in `tokio::spawn`\r\n    |\r\n    = help: within `impl futures::Future`, the trait `std::marker::Send` is not implemented for `Rc<Node>`\r\nnote: future is not `Send` as this value is used across an await\r\n   --> src/main.rs:253:9\r\n    |\r\n238 |     let page = kuchiki::parse_html().one(page);\r\n    |         ---- has type `NodeRef` which is not `Send`\r\n...\r\n253 |         add_url(url).await.unwrap();\r\n    |         ^^^^^^^^^^^^^^^^^^ await occurs here, with `page` maybe used later\r\n...\r\n256 | }\r\n    | - `page` is later dropped here\r\n\r\nerror: aborting due to previous error; 1 warning emitted\r\n\r\nerror: could not compile `get-training-data`\r\n```\r\n\r\nHere is the different code sample that works. Instead of explicitly dropping, I use a block to get the value of `links`. However, I don't see why there should be a different. After-all, in the previous example I explicitly `drop` `page`.\r\n\r\n```\r\nasync fn process(url: Url) -> Result<()> {\r\n    let links = {\r\n        let bytes = fetch(url.clone()).await?;\r\n        // TODO: Is there a way to do this w/o clone?\r\n        let page = String::from_utf8(bytes.clone())?;\r\n        let page = kuchiki::parse_html().one(page);\r\n        let input = get_training_input(&page).ok_or(anyhow!(\"No training input for: {:?}\", url))?;\r\n        let output = get_training_output(&page, &url);\r\n\r\n        get_links(&page, url)\r\n    };\r\n    for url in &links {\r\n        add_url(url).await.unwrap();\r\n    }\r\n    Ok(())\r\n}\r\n```\r\n\r\n### Meta\r\n`rustc --version --verbose`:\r\n```\r\nrustc 1.53.0-nightly (07e0e2ec2 2021-03-24)\r\nbinary: rustc\r\ncommit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597\r\ncommit-date: 2021-03-24\r\nhost: x86_64-unknown-linux-gnu\r\nrelease: 1.53.0-nightly\r\nLLVM version: 12.0.0```", "closed_by": {"login": "jonas-schievink", "id": 1786438, "node_id": "MDQ6VXNlcjE3ODY0Mzg=", "avatar_url": "https://avatars.githubusercontent.com/u/1786438?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jonas-schievink", "html_url": "https://github.com/jonas-schievink", "followers_url": "https://api.github.com/users/jonas-schievink/followers", "following_url": "https://api.github.com/users/jonas-schievink/following{/other_user}", "gists_url": "https://api.github.com/users/jonas-schievink/gists{/gist_id}", "starred_url": "https://api.github.com/users/jonas-schievink/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jonas-schievink/subscriptions", "organizations_url": "https://api.github.com/users/jonas-schievink/orgs", "repos_url": "https://api.github.com/users/jonas-schievink/repos", "events_url": "https://api.github.com/users/jonas-schievink/events{/privacy}", "received_events_url": "https://api.github.com/users/jonas-schievink/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/83631/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/83631/timeline", "performed_via_github_app": null, "state_reason": "completed"}