{"url": "https://api.github.com/repos/rust-lang/rust/issues/90493", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/90493/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/90493/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/90493/events", "html_url": "https://github.com/rust-lang/rust/issues/90493", "id": 1041921744, "node_id": "I_kwDOAAsO6M4-GnbQ", "number": 90493, "title": "The carry in signed carrying_mul on integers should be unsigned", "user": {"login": "dzimmanck", "id": 16160230, "node_id": "MDQ6VXNlcjE2MTYwMjMw", "avatar_url": "https://avatars.githubusercontent.com/u/16160230?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dzimmanck", "html_url": "https://github.com/dzimmanck", "followers_url": "https://api.github.com/users/dzimmanck/followers", "following_url": "https://api.github.com/users/dzimmanck/following{/other_user}", "gists_url": "https://api.github.com/users/dzimmanck/gists{/gist_id}", "starred_url": "https://api.github.com/users/dzimmanck/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dzimmanck/subscriptions", "organizations_url": "https://api.github.com/users/dzimmanck/orgs", "repos_url": "https://api.github.com/users/dzimmanck/repos", "events_url": "https://api.github.com/users/dzimmanck/events{/privacy}", "received_events_url": "https://api.github.com/users/dzimmanck/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 650731663, "node_id": "MDU6TGFiZWw2NTA3MzE2NjM=", "url": "https://api.github.com/repos/rust-lang/rust/labels/C-bug", "name": "C-bug", "color": "f5f1fd", "default": false, "description": "Category: This is a bug."}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2021-11-02T06:17:12Z", "updated_at": "2021-11-03T18:54:04Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "<!--\r\nWhen using carrying_mul to chain multiplies on signed integers, you can get unexpected behavior due to the carry being signed.\r\n-->\r\n\r\nI tried this code:\r\n\r\n```rust\r\n// use signed carry_mul to chain two multiplies (x*y) + (x*y) >> 64\r\nlet carry: i32 = 0;\r\nlet x: i32 = 200000;\r\nlet y: i32 = 100000;\r\nlet (carry, prod) = x.carrying_mul(y, carry);\r\nlet (carry, prod) = x.carrying_mul(y, carry);\r\n\r\n// do the calculation with larger integers\r\nlet large = i64::from(x) * i64::from(y);\r\nlet carry = large - ((large>>32)<<32);\r\nlet expected = ((large + carry)>>32) as i32;\r\n\r\nassert_eq!(expected, prod);\r\n```\r\n\r\nI expected to see this happen: I expected the \"prod\" to be 5.\r\n\r\nInstead, this happened: The product is 4 due to the carry in the first calculation being negative (overflowing) causing it to accumulate incorrectly.\r\n\r\n### Meta\r\n<!--\r\nThis is on a VERY recently updated nightly (as in an hour ago).\r\n-->\r\n\r\n`rustc --version --verbose`:\r\n```\r\nrustc 1.58.0-nightly (db062de72 2021-11-01)\r\nbinary: rustc\r\ncommit-hash: db062de72b0a064f45b6f86894cbdc7c0ec68844\r\ncommit-date: 2021-11-01\r\nhost: x86_64-pc-windows-msvc\r\nrelease: 1.58.0-nightly\r\nLLVM version: 13.0.0\r\n```\r\n\r\n\r\n</p>\r\n</details>\r\n", "closed_by": null, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/90493/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/90493/timeline", "performed_via_github_app": null, "state_reason": null}